version: '3.2'
services:
  springboot:
    build:
      context: ./
      dockerfile: Dockerfile.Springboot
    image: zuhlke/sales-sprinboot-docker-image
    ports:
    - 8080:8080
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
    - spdoc-net

  sp-db:
    build:
      context: ./
      dockerfile: Dockerfile.DB
    image: zuhlke/sales-database-docker-image
    ports:
    - 3306:3306
    environment:
      MYSQL_ROOT_USERNAME: root
      MYSQL_ROOT_PASSWORD: password
    volumes:
    - ./data/db-data:/var/lib/mysql
    - ./data/db-init:/docker-entrypoint-initdb.d
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    networks:
    - spdoc-net

networks:
  spdoc-net: